routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GoalsController;
use App\Http\Controllers\PaymentForecastController;
use App\Http\Controllers\ProvisioningController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth'])->group(function () {

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/', function () {
        return redirect('/dashboard');
    });

    /**
     * Rotas referente usuários
     */
    Route::prefix('users')->group(function (){
        Route::name('users.')->group(function () {
            Route::get('new', [UserController::class, 'register'])->name('new');
            Route::post('store', [UserController::class, 'store'])->name('store');
            Route::get('edit', [UserController::class, 'edit'])->name('edit');
            Route::post('update', [UserController::class, 'update'])->name('update');
        });
    });

    /**
     * Rotas para metas
     */
    Route::prefix('goals')->group(function (){
        Route::name('goals.')->group(function () {
            Route::get('', [GoalsController::class, 'index'])->name('index');
            Route::get('new', [GoalsController::class, 'new'])->name('new');
            Route::post('store', [GoalsController::class, 'store'])->name('store');
            Route::get('edit/{id}', [GoalsController::class, 'edit'])->name('edit');
            Route::post('update/{id}', [GoalsController::class, 'update'])->name('update');
            Route::get('finalize/{id}', [GoalsController::class, 'finalize'])->name('finalize');
            Route::get('reopen/{id}', [GoalsController::class, 'reopen'])->name('reopen');
        });
    });

    /**
     * Rotas para previsão
     */
    Route::prefix('payment-forecast')->group(function (){
        Route::name('payment.forecast.')->group(function () {
            Route::get('', [PaymentForecastController::class, 'index'])->name('index');
            Route::get('new/{provisioningId?}', [PaymentForecastController::class, 'new'])->name('new');
            Route::post('store', [PaymentForecastController::class, 'store'])->name('store');
            Route::get('edit/{id}', [PaymentForecastController::class, 'edit'])->name('edit');
            Route::post('update/{id}', [PaymentForecastController::class, 'update'])->name('update');
            Route::post('pay', [PaymentForecastController::class, 'pay'])->name('pay');
        });
    });

    /**
     * Rotas para provisão
     */
    Route::prefix('provisioning')->group(function (){
        Route::name('provisioning.')->group(function () {
            Route::get('', [ProvisioningController::class, 'index'])->name('index');
            Route::get('new', [ProvisioningController::class, 'new'])->name('new');
            Route::post('store', [ProvisioningController::class, 'store'])->name('store');
            Route::get('edit/{id}', [ProvisioningController::class, 'edit'])->name('edit');
            Route::post('update/{id}', [ProvisioningController::class, 'update'])->name('update');
        });
    });


});

Auth::routes();

app/Models/Provisioning.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Provisioning extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'date',
        'fixed',
        'type',
        'user_id'
    ];
}

app/Http/Controllers/ProvisioningController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Provisioning\Store;
use App\Repository\ProvisioningRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

/***
 * Class ProvisioningController
 *
 * @package App\Http\Controllers
 *
 * @author Jonathan S. Tolotti <jonathanstolotti@gmail.com>
 */

class ProvisioningController extends Controller
{
    /**
     * Retorna listagem de provisões.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        return view('provisioning.index', [
            'provisions' => ProvisioningRepository::getAll()
        ]);
    }

    /**
     * Retorna view de criação de provisão.
     *
     * @return Application|Factory|View
     */
    public function new()
    {
        return view('provisioning.new');
    }

    /**
     * Cria uma nova provisão
     *
     * @param Store $request
     * @return RedirectResponse
     */
    public function store(Store $request): RedirectResponse
    {
        return ProvisioningRepository::store($request);
    }

    /**
     * View de edição da provisão
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function edit(int $id)
    {
        return view('provisioning.edit', [
            'provisioning' => ProvisioningRepository::edit($id)
        ]);
    }

    /**
     * Altera uma provisão
     *
     * @param Store $request
     * @return RedirectResponse
     */
    public function update(Store $request): RedirectResponse
    {
        return ProvisioningRepository::update($request);
    }
}

resources/views/provisioning/edit.blade.php
@extends('adminlte::page')
@section('title', 'Alterar conta')
@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item"><a href="{{route('provisioning.index')}}">Contas</a></li>
                    <li class="breadcrumb-item active">Editar conta</li>
                </ol>
            </div>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row"> <!-- MODELO 3 -->
                <div class="container">
                    <div class="row">
                        <div class="col align-self-start"></div>
                        <div class="col-md-12">
                            <div class="col align-self-center">
                                <div class="card card-dark">
                                    <div class="card-header">
                                        <h3 class="card-title">Nova meta</h3>
                                    </div>
                                    <!-- /.card-header -->
                                    <!-- form start -->
                                    <form method="POST" action="{{ route('provisioning.update', $provisioning['id']) }}" role="form">
                                        @csrf
                                        <div class="card-body">
                                            <div class="form-group">
                                                <!-- NOME -->
                                                <div class="input-group mb-3">
                                                    <input type="text" name="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}"
                                                           value="{{ $provisioning['name'] }}" placeholder="Nome da provisão" autofocus>
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                            <span class="fas fa-file-signature {{ config('adminlte.classes_auth_icon', '') }}"></span>
                                                        </div>
                                                    </div>
                                                    @if($errors->has('name'))
                                                        <div class="invalid-feedback">
                                                            <strong>{{ $errors->first('name') }}</strong>
                                                        </div>
                                                    @endif
                                                </div>

                                                <div class="input-group mb-3">
                                                    <input type="date" name="date" class="form-control value {{ $errors->has('date') ? 'is-invalid' : '' }}"
                                                           value="{{ $provisioning['date'] }}" placeholder="Vencimento">
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                            <span class="fas fa-calendar {{ config('adminlte.classes_auth_icon', '') }}"></span>
                                                        </div>
                                                    </div>
                                                    @if($errors->has('date'))
                                                        <div class="invalid-feedback">
                                                            <strong>{{ $errors->first('date') }}</strong>
                                                        </div>
                                                    @endif
                                                </div>

                                                <div class="input-group mb-3">
                                                    <select name="type" class="form-control {{ $errors->has('type') ? 'is-invalid' : '' }}">
                                                        <option value="INCOME" {{$provisioning['type'] == "INCOME" ? "selected" : ""}}>Receita</option>
                                                        <option value="EXPENSE" {{$provisioning['type'] == "EXPENSE" ? "selected" : ""}}>Despesa</option>
                                                    </select>
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                            <span class="fas fa-clipboard-check {{ config('adminlte.classes_auth_icon', '') }}"></span>
                                                        </div>
                                                    </div>
                                                    @if($errors->has('type'))
                                                        <div class="invalid-feedback">
                                                            <strong>{{ $errors->first('type') }}</strong>
                                                        </div>
                                                    @endif
                                                </div>

                                                <label for="exampleInputPassword1">Lançamento fixo:</label>
                                                <div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success">
                                                    <input name="fixed" type="checkbox" class="custom-control-input" id="customSwitch1" {{$provisioning['fixed'] ? "checked" : ""}}>
                                                    <label class="custom-control-label" for="customSwitch1"></label>
                                                </div>

                                            </div>
                                        </div>
                                        <!-- /.card-body -->

                                        <div class="card-footer">
                                            <div class="row justify-content-end">
                                                <div class="col-md-12">
                                                    <button type="submit" class="btn btn-block {{ config('adminlte.classes_auth_btn', 'btn-flat btn-primary') }}">
                                                        <span class="fas fa-user-plus"></span>
                                                        Cadastrar
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <div class="col align-self-end"></div>
                    </div>
                </div>
            </div> <!-- FIM MODELO 3 -->
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>

@stop

resources/views/provisioning/index.blade.php
@extends('adminlte::page')
@section('title', 'Contas')

@if (session('success'))
    <script>
        window.onload = function() {
            Swal.fire({
                position: 'top-end',
                icon: "success",
                title: "{{session('success')}}",
                showConfirmButton: false,
                timer: 1500
            })
            setInterval(()=>{
                location.reload();
            }, 1500)
        };
    </script>

@endif
@if (session('error'))
    <script>
        window.onload = function() {
            Swal.fire({
                position: 'top-end',
                icon: "error",
                title: "{{session('error')}}",
                showConfirmButton: false,
                timer: 1500
            })
            setInterval(()=>{
                location.reload();
            }, 1500)
        };
    </script>
@endif

@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item active">Contas</li>
                </ol>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Listagem de contas</h3>

                    <div class="card-tools">
                        <div class="input-group">

                            <div class="input-group-append">
                                <a href="{{route('provisioning.new')}}" class="btn btn-success"><i class="fas fa-plus"></i> Adicionar</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                    <table id="provisioning" class="table table-bordered table-hover text-center">
                        <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Vencimento</th>
                            <th>Fixa</th>
                            <th>Tipo</th>
                            <th>Ações</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($provisions as $provision)
                            <tr>
                                <td>{{$provision['name']}}</td>
                                <td>{{$provision['date']}}</td>
                                <td>
                                    <i class="fas fa-thumbs-{{$provision['fixed'] ? "up" : "down"}}"></i>
                                </td>
                                <td>{{$provision['type']}}</td>
                                <td>
                                    <a href="{{route('provisioning.edit', $provision['id'])}}" class="btn btn-info">Editar</a>
                                    <span data-toggle="tooltip" data-placement="top"
                                          title="{{$provision['has_forecast'] ? "Já lançado neste mês" : "Clique para criar uma previsão para este lançamento"}}">
                                        <a href="{{route('payment.forecast.new', $provision['id'])}}"
                                           class="btn {{$provision['has_forecast'] ? "btn-warning" : "btn-success"}}">
                                            <i class='icon fas fa-exclamation-triangle {{$provision['has_forecast'] ? "" : "d-none"}}'></i>
                                            Previsão</a>
                                    </span>

                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                        <tfoot>
                        <tr>
                            <th>Nome</th>
                            <th>Vencimento</th>
                            <th>Fixa</th>
                            <th>Tipo</th>
                            <th>Ações</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
    <input type="hidden" name="_token" id="_token" value="{{@csrf_token()}}">

@stop

@section('js')
    <script src="{{asset('/js/pages/Provisioning/provisioning.js')}}"></script>
@stop

resources/views/provisioning/new.blade.php
@extends('adminlte::page')
@section('title', 'Nova conta')
@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item"><a href="{{route('provisioning.index')}}">Contas</a></li>
                    <li class="breadcrumb-item active">Nova conta</li>
                </ol>
            </div>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row"> <!-- MODELO 3 -->
                <div class="container">
                    <div class="row">
                        <div class="col align-self-start"></div>
                        <div class="col-md-12">
                            <div class="col align-self-center">
                                <div class="card card-dark">
                                    <div class="card-header">
                                        <h3 class="card-title">Nova meta</h3>
                                    </div>
                                    <!-- /.card-header -->
                                    <!-- form start -->
                                    <form method="POST" action="{{ route('provisioning.store') }}" role="form">
                                        @csrf
                                        <div class="card-body">
                                            <div class="form-group">
                                                <!-- NOME -->
                                                <div class="input-group mb-3">
                                                    <input type="text" name="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}"
                                                           value="{{ old('name') }}" placeholder="Nome da provisão" autofocus>
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                            <span class="fas fa-file-signature {{ config('adminlte.classes_auth_icon', '') }}"></span>
                                                        </div>
                                                    </div>
                                                    @if($errors->has('name'))
                                                        <div class="invalid-feedback">
                                                            <strong>{{ $errors->first('name') }}</strong>
                                                        </div>
                                                    @endif
                                                </div>

                                                <div class="input-group mb-3">
                                                    <input type="date" name="date" class="form-control value {{ $errors->has('date') ? 'is-invalid' : '' }}"
                                                           value="{{ old('date') }}" placeholder="Vencimento">
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                            <span class="fas fa-calendar {{ config('adminlte.classes_auth_icon', '') }}"></span>
                                                        </div>
                                                    </div>
                                                    @if($errors->has('date'))
                                                        <div class="invalid-feedback">
                                                            <strong>{{ $errors->first('date') }}</strong>
                                                        </div>
                                                    @endif
                                                </div>

                                                <div class="input-group mb-3">
                                                    <select name="type" class="form-control value {{ $errors->has('type') ? 'is-invalid' : '' }}">
                                                        <option value="INCOME">Receita</option>
                                                        <option value="EXPENSE">Despesa</option>
                                                    </select>
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                            <span class="fas fa-clipboard-check {{ config('adminlte.classes_auth_icon', '') }}"></span>
                                                        </div>
                                                    </div>
                                                    @if($errors->has('type'))
                                                        <div class="invalid-feedback">
                                                            <strong>{{ $errors->first('type') }}</strong>
                                                        </div>
                                                    @endif
                                                </div>

                                                <label for="exampleInputPassword1">Lançamento fixo:</label>
                                                <div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success">
                                                    <input name="fixed" type="checkbox" class="custom-control-input" id="customSwitch1">
                                                    <label class="custom-control-label" for="customSwitch1"></label>
                                                </div>

                                            </div>
                                        </div>
                                        <!-- /.card-body -->

                                        <div class="card-footer">
                                            <div class="row justify-content-end">
                                                <div class="col-md-12">
                                                    <button type="submit" class="btn btn-block {{ config('adminlte.classes_auth_btn', 'btn-flat btn-primary') }}">
                                                        <span class="fas fa-user-plus"></span>
                                                        Cadastrar
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <div class="col align-self-end"></div>
                    </div>
                </div>
            </div> <!-- FIM MODELO 3 -->
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>

@stop