routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GoalsController;
use App\Http\Controllers\PaymentForecastController;
use App\Http\Controllers\ProvisioningController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth'])->group(function () {

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/', function () {
        return redirect('/dashboard');
    });

    /**
     * Rotas referente usuários
     */
    Route::prefix('users')->group(function (){
        Route::name('users.')->group(function () {
            Route::get('new', [UserController::class, 'register'])->name('new');
            Route::post('store', [UserController::class, 'store'])->name('store');
            Route::get('edit', [UserController::class, 'edit'])->name('edit');
            Route::post('update', [UserController::class, 'update'])->name('update');
        });
    });

    /**
     * Rotas para metas
     */
    Route::prefix('goals')->group(function (){
        Route::name('goals.')->group(function () {
            Route::get('', [GoalsController::class, 'index'])->name('index');
            Route::get('new', [GoalsController::class, 'new'])->name('new');
            Route::post('store', [GoalsController::class, 'store'])->name('store');
            Route::get('edit/{id}', [GoalsController::class, 'edit'])->name('edit');
            Route::post('update/{id}', [GoalsController::class, 'update'])->name('update');
            Route::get('finalize/{id}', [GoalsController::class, 'finalize'])->name('finalize');
            Route::get('reopen/{id}', [GoalsController::class, 'reopen'])->name('reopen');
        });
    });

    /**
     * Rotas para previsão
     */
    Route::prefix('payment-forecast')->group(function (){
        Route::name('payment.forecast.')->group(function () {
            Route::get('', [PaymentForecastController::class, 'index'])->name('index');
            Route::get('new/{provisioningId?}', [PaymentForecastController::class, 'new'])->name('new');
            Route::post('store', [PaymentForecastController::class, 'store'])->name('store');
            Route::get('edit/{id}', [PaymentForecastController::class, 'edit'])->name('edit');
            Route::post('update/{id}', [PaymentForecastController::class, 'update'])->name('update');
            Route::post('pay', [PaymentForecastController::class, 'pay'])->name('pay');
        });
    });

    /**
     * Rotas para provisão
     */
    Route::prefix('provisioning')->group(function (){
        Route::name('provisioning.')->group(function () {
            Route::get('', [ProvisioningController::class, 'index'])->name('index');
            Route::get('new', [ProvisioningController::class, 'new'])->name('new');
            Route::post('store', [ProvisioningController::class, 'store'])->name('store');
            Route::get('edit/{id}', [ProvisioningController::class, 'edit'])->name('edit');
            Route::post('update/{id}', [ProvisioningController::class, 'update'])->name('update');
        });
    });


});

Auth::routes();

resources/views/forecasts/edit.blade.php
@extends('adminlte::page')
@section('title', 'Editar previsão')
@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item"><a href="{{route('payment.forecast.index')}}">Previsão</a></li>
                    <li class="breadcrumb-item active">Editar previsão</li>
                </ol>
            </div>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="row"> <!-- MODELO 3 -->
                <div class="container">
                    <div class="row">
                        <div class="col align-self-start"></div>
                        <div class="col-md-12">
                            <div class="col align-self-center">
                                <div class="card card-dark">
                                    <div class="card-header">
                                        <h3 class="card-title">Editar previsão - {{$forecast->name}}</h3>
                                    </div>
                                    <!-- /.card-header -->
                                    <!-- form start -->
                                    <form method="POST" action="{{ route('payment.forecast.update', $forecast['id']) }}" role="form" enctype="multipart/form-data">
                                        @csrf
                                        <div class="card-body">
                                            <div class="form-group">
                                                <!-- NOME -->
                                                <div class="input-group mb-3">
                                                    <input type="text" name="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}"
                                                           value="{{ $forecast->name }}" placeholder="Valor do lançamento" readonly>
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                            <span class="fas fa-money-bill {{ config('adminlte.classes_auth_icon', '') }}"></span>
                                                        </div>
                                                    </div>
                                                    @if($errors->has('name'))
                                                        <div class="invalid-feedback">
                                                            <strong>{{ $errors->first('name') }}</strong>
                                                        </div>
                                                    @endif
                                                </div>

                                                <div class="input-group mb-3">
                                                    <input type="date" name="due_date" class="form-control {{ $errors->has('due_date') ? 'is-invalid' : '' }}"
                                                           value="{{$forecast->due_date}}" placeholder="Vencimento">
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                            <span class="fas fa-calendar {{ config('adminlte.classes_auth_icon', '') }}"></span>
                                                        </div>
                                                    </div>
                                                    @if($errors->has('due_date'))
                                                        <div class="invalid-feedback">
                                                            <strong>{{ $errors->first('due_date') }}</strong>
                                                        </div>
                                                    @endif
                                                </div>

                                                <div class="input-group mb-3">
                                                    <input type="text" name="value" class="form-control value {{ $errors->has('value') ? 'is-invalid' : '' }}"
                                                           value="{{ number_format($forecast->value, 2, ',', '.') }}" placeholder="Valor do lançamento">
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                            <span class="fas fa-money-bill {{ config('adminlte.classes_auth_icon', '') }}"></span>
                                                        </div>
                                                    </div>
                                                    @if($errors->has('value'))
                                                        <div class="invalid-feedback">
                                                            <strong>{{ $errors->first('value') }}</strong>
                                                        </div>
                                                    @endif
                                                </div>

                                                @if (! $forecast->link_invoice)
                                                <div class="form-group">
                                                    <div class="custom-file">
                                                        <input type="file" name="invoice" class="custom-file-input" id="customFile">
                                                        <label class="custom-file-label" for="customFile" content="Procurar">Selecione o boleto bancário...</label>
                                                    </div>
                                                </div>
                                                @endif

                                            </div>
                                        </div>
                                        <!-- /.card-body -->

                                        <div class="card-footer">
                                            <div class="row justify-content-end">
                                                <div class="col-md-12">
                                                    <button type="submit" class="btn btn-block {{ config('adminlte.classes_auth_btn', 'btn-flat btn-primary') }}">
                                                        <span class="fas fa-user-plus"></span>
                                                        Cadastrar
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <div class="col align-self-end"></div>
                    </div>
                </div>
            </div> <!-- FIM MODELO 3 -->
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>

@stop

@section('js')
    <script src="{{asset('/js/helpers/jquery.mask.js')}}"></script>
    <script src="{{asset('/js/pages/Forecasts/forecasts.js')}}"></script>
@stop

resources/views/forecasts/index.blade.php
@extends('adminlte::page')
@section('title', 'Previsão')

@if (session('success'))
    <script>
        window.onload = function() {
            Swal.fire({
                position: 'top-end',
                icon: "success",
                title: "{{session('success')}}",
                showConfirmButton: false,
                timer: 1500
            })
            setInterval(()=>{
                location.reload();
            }, 1500)
        };
    </script>

@endif
@if (session('error'))
    <script>
        window.onload = function() {
            Swal.fire({
                position: 'top-end',
                icon: "error",
                title: "{{session('error')}}",
                showConfirmButton: false,
                timer: 1500
            })
            setInterval(()=>{
                location.reload();
            }, 1500)
        };
    </script>
@endif
@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item active">Previsão</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Lançamentos</h3>

                    <div class="card-tools">
                        <div class="input-group">

                            <div class="input-group-append">
                                <a href="{{route('payment.forecast.new')}}" class="btn btn-success"><i class="fas fa-plus"></i> Adicionar</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                    <table id="goals" class="table table-bordered table-hover text-center">
                        <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Vencimento</th>
                            <th>Status</th>
                            <th>Data pagamento</th>
                            <th>Valor</th>
                            <th>Boleto</th>
                            <th>Ações</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($forecasts as $forecast)
                            <tr>
                                <td>
                                    {{$forecast['name']}}
                                </td>
                                <td>
                                    {{date("d/m/Y", strtotime($forecast['due_date']))}}
                                </td>
                                <td>
                                    @if($forecast['paid'])
                                        <span class="badge alert-success">Pago</span>
                                    @elseif(! $forecast['paid'] && strtotime(date('Y-m-d')) == strtotime($forecast['due_date']))
                                        <button class="btn btn-sm badge alert-warning" data-toggle="tooltip" data-placement="top" title="Clique para pagar"
                                                onclick="payForecast(
                                                    '{{$forecast['name']}}',
                                                    '{{date("d/m/Y", strtotime($forecast['due_date']))}}',
                                                    '{{number_format($forecast['value'], 2, ',', '.')}}',
                                                    '{{$forecast['id']}}',
                                                    '{{route('payment.forecast.pay')}}'
                                                    )">Pagar
                                        </button>
                                    @elseif(! $forecast['paid'] && strtotime(date('Y-m-d')) > strtotime($forecast['due_date']))
                                        <button class="btn btn-sm badge alert-danger" data-toggle="tooltip" data-placement="top" title="Clique para pagar"
                                                onclick="payForecast(
                                                    '{{$forecast['name']}}',
                                                    '{{date("d/m/Y", strtotime($forecast['due_date']))}}',
                                                    '{{number_format($forecast['value'], 2, ',', '.')}}',
                                                    '{{$forecast['id']}}',
                                                    '{{route('payment.forecast.pay')}}'
                                                    )">Vencido
                                        </button>
                                    @elseif(! $forecast['paid'] && strtotime(date('Y-m-d')) < strtotime($forecast['due_date']))
                                        <button class="btn btn-sm badge alert-info" data-toggle="tooltip" data-placement="top" title="Clique para pagar"
                                                onclick="payForecast(
                                                    '{{$forecast['name']}}',
                                                    '{{date("d/m/Y", strtotime($forecast['due_date']))}}',
                                                    '{{number_format($forecast['value'], 2, ',', '.')}}',
                                                    '{{$forecast['id']}}',
                                                    '{{route('payment.forecast.pay')}}'
                                                    )">Pendente
                                        </button>
                                    @endif

                                </td>
                                <td>
                                    @if($forecast['payment_date'])
                                        {{date("d/m/Y H:i:s", strtotime($forecast['payment_date']))}}
                                    @else
                                        <span class="badge alert-info">Pendente</span>
                                    @endif
                                </td>
                                <td>
                                    R$ {{number_format($forecast['value'], 2, ',', '.')}}
                                </td>
                                <td>
                                    @if($forecast['link_invoice'])
                                        <a href="{{asset(Storage::url($forecast['link_invoice']))}}" target="_blank" data-toggle="tooltip" data-placement="top" title="Clique para visualizar o boleto">
                                            <i class="fas fa-file-invoice"></i>
                                        </a>
                                    @else
                                        <i class="fas fa-minus-circle" data-toggle="tooltip" data-placement="top" title="Não há boleto disponível"></i>
                                    @endif
                                </td>
                                <td>
                                   <a href="{{route('payment.forecast.edit', $forecast['id'])}}" class="btn btn-info">Editar</a>
                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                        <tfoot>
                        <tr>
                            <th>Nome</th>
                            <th>Vencimento</th>
                            <th>Status</th>
                            <th>Data pagamento</th>
                            <th>Valor</th>
                            <th>Boleto</th>
                            <th>Ações</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
    <input type="hidden" name="_token" id="_token" value="{{@csrf_token()}}">
@stop

@section('js')
    <script src="{{asset('/js/pages/Forecasts/forecasts.js')}}"></script>
@stop

resources/views/forecasts/new.blade.php
@extends('adminlte::page')
@section('title', 'Nova previsão')
@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item"><a href="{{route('payment.forecast.index')}}">Previsão</a></li>
                    <li class="breadcrumb-item active">Nova previsão</li>
                </ol>
            </div>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row"> <!-- MODELO 3 -->
                <div class="container">
                    <div class="row">
                        <div class="col align-self-start"></div>
                        <div class="col-md-12">
                            <div class="col align-self-center">
                                <div class="card card-dark">
                                    <div class="card-header">
                                        <h3 class="card-title">Nova previsão</h3>
                                    </div>
                                    <!-- /.card-header -->
                                    <!-- form start -->
                                    <form method="POST" action="{{ route('payment.forecast.store') }}" role="form" enctype="multipart/form-data">
                                        @csrf
                                        <div class="card-body">
                                            <div class="form-group">
                                                <!-- NOME -->
                                                <div class="input-group mb-3">
                                                    <select name="provisioning" class="form-control select2 {{ $errors->has('provisioning_name') ? 'is-invalid' : '' }}">
                                                        <option selected disabled>Selecione</option>
                                                        @foreach($allProvisioning as $provisioning)
                                                            <option value="{{$provisioning['id']}}" {{isset($currentProvisioning['id']) && $currentProvisioning['id'] == $provisioning['id'] ? "selected" : ""}}>{{$provisioning['name']}}</option>
                                                        @endforeach
                                                    </select>
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                            <span class="fas fa-clipboard-check {{ config('adminlte.classes_auth_icon', '') }}"></span>
                                                        </div>
                                                    </div>
                                                    @if($errors->has('provisioning_name'))
                                                        <div class="invalid-feedback">
                                                            <strong>{{ $errors->first('provisioning_name') }}</strong>
                                                        </div>
                                                    @endif
                                                </div>

                                                <div class="input-group mb-3">
                                                    <input type="date" name="due_date" class="form-control {{ $errors->has('due_date') ? 'is-invalid' : '' }}"
                                                           value="{{ isset($currentProvisioning->date) ? date('Y-m-d', strtotime($currentProvisioning->date)) : ""}}" placeholder="Vencimento">
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                            <span class="fas fa-calendar {{ config('adminlte.classes_auth_icon', '') }}"></span>
                                                        </div>
                                                    </div>
                                                    @if($errors->has('due_date'))
                                                        <div class="invalid-feedback">
                                                            <strong>{{ $errors->first('due_date') }}</strong>
                                                        </div>
                                                    @endif
                                                </div>

                                                <div class="input-group mb-3">
                                                    <input type="text" name="value" class="form-control value {{ $errors->has('value') ? 'is-invalid' : '' }}"
                                                           value="{{ old('value') }}" placeholder="Valor do lançamento">
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                            <span class="fas fa-money-bill {{ config('adminlte.classes_auth_icon', '') }}"></span>
                                                        </div>
                                                    </div>
                                                    @if($errors->has('value'))
                                                        <div class="invalid-feedback">
                                                            <strong>{{ $errors->first('value') }}</strong>
                                                        </div>
                                                    @endif
                                                </div>

                                                <div class="form-group">

                                                    <div class="custom-file">
                                                        <input type="file" name="invoice" class="custom-file-input" id="customFile">
                                                        <label class="custom-file-label" for="customFile" content="Procurar">Selecione o boleto bancário...</label>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <!-- /.card-body -->

                                        <div class="card-footer">
                                            <div class="row justify-content-end">
                                                <div class="col-md-12">
                                                    <button type="submit" class="btn btn-block {{ config('adminlte.classes_auth_btn', 'btn-flat btn-primary') }}">
                                                        <span class="fas fa-user-plus"></span>
                                                        Cadastrar
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <div class="col align-self-end"></div>
                    </div>
                </div>
            </div> <!-- FIM MODELO 3 -->
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>

@stop

@section('js')
    <script src="{{asset('/js/helpers/jquery.mask.js')}}"></script>
    <script src="{{asset('/js/pages/Forecasts/forecasts.js')}}"></script>
@stop