routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GoalsController;
use App\Http\Controllers\PaymentForecastController;
use App\Http\Controllers\ProvisioningController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth'])->group(function () {

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/', function () {
        return redirect('/dashboard');
    });

    /**
     * Rotas referente usuários
     */
    Route::prefix('users')->group(function (){
        Route::name('users.')->group(function () {
            Route::get('new', [UserController::class, 'register'])->name('new');
            Route::post('store', [UserController::class, 'store'])->name('store');
            Route::get('edit', [UserController::class, 'edit'])->name('edit');
            Route::post('update', [UserController::class, 'update'])->name('update');
        });
    });

    /**
     * Rotas para metas
     */
    Route::prefix('goals')->group(function (){
        Route::name('goals.')->group(function () {
            Route::get('', [GoalsController::class, 'index'])->name('index');
            Route::get('new', [GoalsController::class, 'new'])->name('new');
            Route::post('store', [GoalsController::class, 'store'])->name('store');
            Route::get('edit/{id}', [GoalsController::class, 'edit'])->name('edit');
            Route::post('update/{id}', [GoalsController::class, 'update'])->name('update');
            Route::get('finalize/{id}', [GoalsController::class, 'finalize'])->name('finalize');
            Route::get('reopen/{id}', [GoalsController::class, 'reopen'])->name('reopen');
        });
    });

    /**
     * Rotas para previsão
     */
    Route::prefix('payment-forecast')->group(function (){
        Route::name('payment.forecast.')->group(function () {
            Route::get('', [PaymentForecastController::class, 'index'])->name('index');
            Route::get('new/{provisioningId?}', [PaymentForecastController::class, 'new'])->name('new');
            Route::post('store', [PaymentForecastController::class, 'store'])->name('store');
            Route::get('edit/{id}', [PaymentForecastController::class, 'edit'])->name('edit');
            Route::post('update/{id}', [PaymentForecastController::class, 'update'])->name('update');
            Route::post('pay', [PaymentForecastController::class, 'pay'])->name('pay');
        });
    });

    /**
     * Rotas para provisão
     */
    Route::prefix('provisioning')->group(function (){
        Route::name('provisioning.')->group(function () {
            Route::get('', [ProvisioningController::class, 'index'])->name('index');
            Route::get('new', [ProvisioningController::class, 'new'])->name('new');
            Route::post('store', [ProvisioningController::class, 'store'])->name('store');
            Route::get('edit/{id}', [ProvisioningController::class, 'edit'])->name('edit');
            Route::post('update/{id}', [ProvisioningController::class, 'update'])->name('update');
        });
    });


});

Auth::routes();

app/Http/Controllers/GoalsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Goals\Store;
use App\Models\UserGoal;
use App\Repository\GoalRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class GoalsController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $goals = GoalRepository::getAllGoals();

        return view('goals.index', [
            'goals' => $goals
        ]);
    }

    /**
     * Retorna view de criação de metas
     *
     * @return Application|Factory|View
     */
    public function new()
    {
        return view('goals.new');
    }

    /**
     * @param Store $request
     * @return RedirectResponse
     */
    public function store(Store $request): RedirectResponse
    {
        return GoalRepository::createGoal($request);
    }

    /**
     * Retorna view de edição da meta
     *
     * @param int $goalId
     * @return Application|Factory|View
     */
    public function edit(int $goalId)
    {
        $goal = GoalRepository::getGoal($goalId);

        return view('goals.edit', ['goal' => $goal]);
    }

    /**
     * Altera dados de uma meta
     *
     * @param Store $request
     * @return RedirectResponse
     */
    public function update(Store $request): RedirectResponse
    {
        return GoalRepository::updateGoal($request);
    }

    /**
     * Finaliza uma entrega
     *
     * @param int $goalId
     * @return RedirectResponse
     */
    public function finalize(int $goalId): RedirectResponse
    {
        return GoalRepository::finalize($goalId);
    }

    /**
     * Reabre uma entrega
     *
     * @param int $goalId
     * @return RedirectResponse
     */
    public function reopen(int $goalId): RedirectResponse
    {
        return GoalRepository::reopen($goalId);
    }
}

resources/views/goals/edit.blade.php
@extends('adminlte::page')
@section('title', 'Nova meta')
@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item"><a href="{{route('goals.index')}}">Metas</a></li>
                    <li class="breadcrumb-item active">Editar meta</li>
                </ol>
            </div>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="row"> <!-- MODELO 3 -->
                <div class="container">
                    <div class="row">
                        <div class="col align-self-start"></div>
                        <div class="col-md-12">
                            <div class="col align-self-center">
                                <div class="card card-dark">
                                    <div class="card-header">
                                        <h3 class="card-title">Editar meta</h3>
                                    </div>
                                    <!-- /.card-header -->
                                    <!-- form start -->
                                    <form method="POST" action="{{ route('goals.update', $goal->id) }}" role="form">
                                        @csrf
                                        <div class="card-body">
                                            <div class="form-group">
                                                <!-- NOME -->
                                                <div class="input-group mb-3">
                                                    <input type="date" name="start_date" class="form-control {{ $errors->has('start_date') ? 'is-invalid' : '' }}"
                                                           value="{{$goal->start_date}}" autofocus>
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                            <span class="fas fa-calendar {{ config('adminlte.classes_auth_icon', '') }}"></span>
                                                        </div>
                                                    </div>
                                                    @if($errors->has('start_date'))
                                                        <div class="invalid-feedback">
                                                            <strong>{{ $errors->first('start_date') }}</strong>
                                                        </div>
                                                    @endif
                                                </div>

                                                <div class="input-group mb-3">
                                                    <input type="text" name="value" class="form-control value {{ $errors->has('value') ? 'is-invalid' : '' }}"
                                                           value="{{ number_format($goal->value, 2, ',', '.') }}" placeholder="Valor da meta">
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                            <span class="fas fa-money-bill {{ config('adminlte.classes_auth_icon', '') }}"></span>
                                                        </div>
                                                    </div>
                                                    @if($errors->has('value'))
                                                        <div class="invalid-feedback">
                                                            <strong>{{ $errors->first('value') }}</strong>
                                                        </div>
                                                    @endif
                                                </div>

                                            </div>
                                        </div>
                                        <!-- /.card-body -->

                                        <div class="card-footer">
                                            <div class="row justify-content-end">
                                                <div class="col-md-12">
                                                    <button type="submit" class="btn btn-block {{ config('adminlte.classes_auth_btn', 'btn-flat btn-primary') }}">
                                                        <span class="fas fa-user-plus"></span>
                                                        Alterar
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <div class="col align-self-end"></div>
                    </div>
                </div>
            </div> <!-- FIM MODELO 3 -->
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
@stop

@section('js')
    <script src="{{asset('/js/helpers/jquery.mask.js')}}"></script>
    <script src="{{asset('/js/pages/Goals/goals.js')}}"></script>
@stop

resources/views/goals/index.blade.php
@extends('adminlte::page')
@section('title', 'Metas')

@if (session('success'))
    <script>
        window.onload = function() {
            Swal.fire({
                position: 'top-end',
                icon: "success",
                title: "{{session('success')}}",
                showConfirmButton: false,
                timer: 1500
            })
            setInterval(()=>{
                location.reload();
            }, 1500)
        };
    </script>

@endif
@if (session('error'))
    <script>
        window.onload = function() {
            Swal.fire({
                position: 'top-end',
                icon: "error",
                title: "{{session('error')}}",
                showConfirmButton: false,
                timer: 1500
            })
            setInterval(()=>{
                location.reload();
            }, 1500)
        };
    </script>
@endif
@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item active">Metas</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Listagem de metas</h3>

                    <div class="card-tools">
                        <div class="input-group">

                            <div class="input-group-append">
                                <a href="{{route('goals.new')}}" class="btn btn-success"><i class="fas fa-plus"></i> Adicionar</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                    <table id="goals" class="table table-bordered table-hover text-center">
                        <thead>
                        <tr>
                            <th>Mês</th>
                            <th>Valor</th>
                            <th>Status</th>
                            <th>Ações</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($goals as $goal)
                            <tr>
                                <td>{{$goal['start_date']}}</td>
                                <td>{{number_format($goal['value'], 2, ',', '.')}}</td>
                                <td>
                                    <i class="fas fa-thumbs-{{$goal['reach'] ? "up" : "down"}}"></i>
                                </td>
                                <td>
                                    <a href="{{route('goals.edit', $goal['id'])}}" class="btn btn-info btn-sm">Editar</a>
                                    @if (! $goal['reach'])
                                        <a href="{{route('goals.finalize', $goal['id'])}}" class="btn btn-success btn-sm">Finalizar</a>
                                    @else
                                        <a href="{{route('goals.reopen', $goal['id'])}}" class="btn btn-warning btn-sm">Reabrir</a>
                                    @endif

                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                        <tfoot>
                        <tr>
                            <th>Mês</th>
                            <th>Valor</th>
                            <th>Status</th>
                            <th>Ações</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
    <input type="hidden" name="_token" id="_token" value="{{@csrf_token()}}">
@stop

@section('js')
    <script src="{{asset('/js/pages/Goals/goals.js')}}"></script>
@stop

resources/views/goals/new.blade.php
@extends('adminlte::page')
@section('title', 'Nova meta')

@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item"><a href="{{route('goals.index')}}">Metas</a></li>
                    <li class="breadcrumb-item active">Nova meta</li>
                </ol>
            </div>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="row"> <!-- MODELO 3 -->
                <div class="container">
                    <div class="row">
                        <div class="col align-self-start"></div>
                        <div class="col-md-12">
                            <div class="col align-self-center">
                                <div class="card card-dark">
                                    <div class="card-header">
                                        <h3 class="card-title">Nova meta</h3>
                                    </div>
                                    <!-- /.card-header -->
                                    <!-- form start -->
                                    <form method="POST" action="{{ route('goals.store') }}" role="form">
                                        @csrf
                                        <div class="card-body">
                                            <div class="form-group">
                                                <!-- NOME -->
                                                <div class="input-group mb-3">
                                                    <input type="date" name="start_date" class="form-control {{ $errors->has('start_date') ? 'is-invalid' : '' }}"
                                                           value="{{ old('start_date') }}" autofocus>
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                            <span class="fas fa-calendar {{ config('adminlte.classes_auth_icon', '') }}"></span>
                                                        </div>
                                                    </div>
                                                    @if($errors->has('start_date'))
                                                        <div class="invalid-feedback">
                                                            <strong>{{ $errors->first('start_date') }}</strong>
                                                        </div>
                                                    @endif
                                                </div>

                                                <div class="input-group mb-3">
                                                    <input type="text" name="value" class="form-control value {{ $errors->has('value') ? 'is-invalid' : '' }}"
                                                           value="{{ old('value') }}" placeholder="Valor da meta">
                                                    <div class="input-group-append">
                                                        <div class="input-group-text">
                                                            <span class="fas fa-money-bill {{ config('adminlte.classes_auth_icon', '') }}"></span>
                                                        </div>
                                                    </div>
                                                    @if($errors->has('value'))
                                                        <div class="invalid-feedback">
                                                            <strong>{{ $errors->first('value') }}</strong>
                                                        </div>
                                                    @endif
                                                </div>

                                            </div>
                                        </div>
                                        <!-- /.card-body -->

                                        <div class="card-footer">
                                            <div class="row justify-content-end">
                                                <div class="col-md-12">
                                                    <button type="submit" class="btn btn-block {{ config('adminlte.classes_auth_btn', 'btn-flat btn-primary') }}">
                                                        <span class="fas fa-user-plus"></span>
                                                        {{ __('adminlte::adminlte.register') }}
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <div class="col align-self-end"></div>
                    </div>
                </div>
            </div> <!-- FIM MODELO 3 -->
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
@stop

@section('js')
    <script src="{{asset('/js/helpers/jquery.mask.js')}}"></script>
    <script src="{{asset('/js/pages/Goals/goals.js')}}"></script>
@stop